services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
    ports:
      - 8080:8080
    env_file:
      - ".env"
    networks:
      - backend
    volumes:
      - .:/usr/src/app

  postgresql:
    image: postgres:15-alpine
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
    expose:
      - 5432
    ports:
      - 5432:5432
    env_file:
      - ".env"
    networks:
      - backend
    
networks:
  backend:
    driver: bridge
